version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package samTemplate.yaml --s3-bucket lambdapipeline-bucket-1 --output-template-file outputsamtemplate.yml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputsamtemplate.yml
